RSGShared = RSGShared or {}
RSGShared.Weapons = {
    -- revolver
    [`weapon_revolver_cattleman`]              = { name = 'weapon_revolver_cattleman',              label = 'Cattleman Revolver',                 weapontype = 'Revolver',     ammotype = 'AMMO_REVOLVER', damagereason = 'Shot by a Cattleman Revolver' },
    [`weapon_revolver_cattleman_mexican`]      = { name = 'weapon_revolver_cattleman_mexican',      label = 'Cattleman Mexican Revolver',         weapontype = 'Revolver',     ammotype = 'AMMO_REVOLVER', damagereason = 'Shot by a Cattleman Mexican Revolver' },
    [`weapon_revolver_doubleaction`]           = { name = 'weapon_revolver_doubleaction',           label = 'Double Action Revolver',             weapontype = 'Revolver',     ammotype = 'AMMO_REVOLVER', damagereason = 'Shot by a Double Action Revolver' },
    [`weapon_revolver_doubleaction_gambler`]   = { name = 'weapon_revolver_doubleaction_gambler',   label = 'Double Action Gambler Revolver',     weapontype = 'Revolver',     ammotype = 'AMMO_REVOLVER', damagereason = 'Shot by a Double Action Gambler Revolver' },
    [`weapon_revolver_schofield`]              = { name = 'weapon_revolver_schofield',              label = 'Schofield Revolver',                 weapontype = 'Revolver',     ammotype = 'AMMO_REVOLVER', damagereason = 'Shot by a Schofield Revolver' },
    [`weapon_revolver_lemat`]                  = { name = 'weapon_revolver_lemat',                  label = 'Lemat Revolver',                     weapontype = 'Revolver',     ammotype = 'AMMO_REVOLVER', damagereason = 'Shot by a Lemat Revolver' },
    [`weapon_revolver_navy`]                   = { name = 'weapon_revolver_navy',                   label = 'Navy Revolver',                      weapontype = 'Revolver',     ammotype = 'AMMO_REVOLVER', damagereason = 'Shot by a Navy Revolver' },
    [`weapon_revolver_navy_crossover`]         = { name = 'weapon_revolver_navy_crossover',         label = 'Navy Crossover Revolver',            weapontype = 'Revolver',     ammotype = 'AMMO_REVOLVER', damagereason = 'Shot by a Navy Crossover Revolver' },
    -- pistol
    [`weapon_pistol_volcanic`]                 = { name = 'weapon_pistol_volcanic',                 label = 'Volcanic Pistol',                    weapontype = 'Pistol',       ammotype = 'AMMO_PISTOL',   damagereason = 'Shot by a Volcanic Pistol' },
    [`weapon_pistol_m1899`]                    = { name = 'weapon_pistol_m1899',                    label = 'm1899 Pistol',                       weapontype = 'Pistol',       ammotype = 'AMMO_PISTOL',   damagereason = 'Shot by an m1899 Pistol' },
    [`weapon_pistol_mauser`]                   = { name = 'weapon_pistol_mauser',                   label = 'Mauser Pistol',                      weapontype = 'Pistol',       ammotype = 'AMMO_PISTOL',   damagereason = 'Shot by a Mauser Pistol' },
    [`weapon_pistol_semiauto`]                 = { name = 'weapon_pistol_semiauto',                 label = 'Semi-Auto Pistol',                   weapontype = 'Pistol',       ammotype = 'AMMO_PISTOL',   damagereason = 'Shot by a Semi-Auto Pistol' },
    -- repeater
    [`weapon_repeater_carbine`]                = { name = 'weapon_repeater_carbine',                label = 'Carbine Repeater',                   weapontype = 'Repeater',     ammotype = 'AMMO_REPEATER', damagereason = 'Shot by a Carbine Repeater' },
    [`weapon_repeater_winchester`]             = { name = 'weapon_repeater_winchester',             label = 'Winchester Repeater',                weapontype = 'Repeater',     ammotype = 'AMMO_REPEATER', damagereason = 'Shot by a Winchester Repeater' },
    [`weapon_repeater_henry`]                  = { name = 'weapon_repeater_henry',                  label = 'Henry Repeater',                     weapontype = 'Repeater',     ammotype = 'AMMO_REPEATER', damagereason = 'Shot by a Henry Repeater' },
    [`weapon_repeater_evans`]                  = { name = 'weapon_repeater_evans',                  label = 'Evans Repeater',                     weapontype = 'Repeater',     ammotype = 'AMMO_REPEATER', damagereason = 'Shot by an Evans Repeater' },
    -- rifle
    [`weapon_rifle_varmint`]                   = { name = 'weapon_rifle_varmint',                   label = 'Varmint Rifle',                      weapontype = 'Rifle',        ammotype = 'AMMO_RIFLE',    damagereason = 'Shot by a Varmint Rifle' },
    [`weapon_rifle_springfield`]               = { name = 'weapon_rifle_springfield',               label = 'Springfield Rifle',                  weapontype = 'Rifle',        ammotype = 'AMMO_RIFLE',    damagereason = 'Shot by a Springfield Rifle' },
    [`weapon_rifle_boltaction`]                = { name = 'weapon_rifle_boltaction',                label = 'Boltaction Rifle',                   weapontype = 'Rifle',        ammotype = 'AMMO_RIFLE',    damagereason = 'Shot by a Bolt Action Rifle' },
    [`weapon_rifle_elephant`]                  = { name = 'weapon_rifle_elephant',                  label = 'Elephant Rifle',                     weapontype = 'Rifle',        ammotype = 'AMMO_RIFLE',    damagereason = 'Shot by an Elephant Rifle' },
    -- sniperrifle
    [`weapon_sniperrifle_rollingblock`]        = { name = 'weapon_sniperrifle_rollingblock',        label = 'Rollingblock Sniper Rifle',          weapontype = 'Sniper Rifle', ammotype = 'AMMO_RIFLE',    damagereason = 'Shot by a Rolling Block Rifle' },
    [`weapon_sniperrifle_rollingblock_exotic`] = { name = 'weapon_sniperrifle_rollingblock_exotic', label = 'Rollingblock Exotic Sniper Rifle',   weapontype = 'Sniper Rifle', ammotype = 'AMMO_RIFLE',    damagereason = 'Shot by an Exotic Rolling Block Rifle' },
    [`weapon_sniperrifle_carcano`]             = { name = 'weapon_sniperrifle_carcano',             label = 'Rollingblock Carcano Sniper Rifle',  weapontype = 'Sniper Rifle', ammotype = 'AMMO_RIFLE',    damagereason = 'Shot by a Carcano Rifle' },
    -- shotgun
    [`weapon_shotgun_doublebarrel`]            = { name = 'weapon_shotgun_doublebarrel',            label = 'Double Barrel Shotgun',              weapontype = 'Shotgun',      ammotype = 'AMMO_SHOTGUN',  damagereason = 'Shot by a Double Barrel Shotgun' },
    [`weapon_shotgun_doublebarrel_exotic`]     = { name = 'weapon_shotgun_doublebarrel_exotic',     label = 'Double Barrel Exotic Shotgun',       weapontype = 'Shotgun',      ammotype = 'AMMO_SHOTGUN',  damagereason = 'Shot by an Exotic Double Barrel Shotgun' },
    [`weapon_shotgun_sawedoff`]                = { name = 'weapon_shotgun_sawedoff',                label = 'Sawedoff Shotgun',                   weapontype = 'Shotgun',      ammotype = 'AMMO_SHOTGUN',  damagereason = 'Shot by a Sawed-Off Shotgun' },
    [`weapon_shotgun_semiauto`]                = { name = 'weapon_shotgun_semiauto',                label = 'Semi-Auto Shotgun',                  weapontype = 'Shotgun',      ammotype = 'AMMO_SHOTGUN',  damagereason = 'Shot by a Semi-Auto Shotgun' },
    [`weapon_shotgun_pump`]                    = { name = 'weapon_shotgun_pump',                    label = 'Pump Action Shotgun',                weapontype = 'Shotgun',      ammotype = 'AMMO_SHOTGUN',  damagereason = 'Shot by a Pump Shotgun' },
    [`weapon_shotgun_repeating`]               = { name = 'weapon_shotgun_repeating',               label = 'Repeating Shotgun',                  weapontype = 'Shotgun',      ammotype = 'AMMO_SHOTGUN',  damagereason = 'Shot by a Repeating Shotgun' },
    -- bow
    [`weapon_bow`]                             = { name = 'weapon_bow',                             label = 'Sandard Bow',                        weapontype = 'Bow',          ammotype = 'AMMO_ARROW',    damagereason = 'Hit by an arrow' },
    [`weapon_bow_improved`]                    = { name = 'weapon_bow_improved',                    label = 'Improved Bow',                       weapontype = 'Bow',          ammotype = 'AMMO_ARROW',    damagereason = 'Hit by an improved bow' },
    -- lasso
    [`weapon_lasso`]                           = { name = 'weapon_lasso',                           label = 'Sandard Lasso',                      weapontype = 'Lasso',        ammotype = nil,             damagereason = 'Caught with a lasso' },
    [`weapon_lasso_reinforced`]                = { name = 'weapon_lasso_reinforced',                label = 'Reinforced Lasso',                   weapontype = 'Lasso',        ammotype = nil,             damagereason = 'Caught with a reinforced lasso' },
    -- melee / knife
    [`weapon_melee_knife`]                     = { name = 'weapon_melee_knife',                     label = 'Sandard Knife',                      weapontype = 'Melee',        ammotype = nil,             damagereason = 'Cut by a knife' },
    [`weapon_melee_knife_jawbone`]             = { name = 'weapon_melee_knife_jawbone',             label = 'Jawbon Knife',                       weapontype = 'Melee',        ammotype = nil,             damagereason = 'Cut by a jawbone knife' },
    [`weapon_melee_knife_trader`]              = { name = 'weapon_melee_knife_trader',              label = 'Tader Knife',                        weapontype = 'Melee',        ammotype = nil,             damagereason = 'Cut by a trader knife' },
    [`weapon_melee_knife_horror`]              = { name = 'weapon_melee_knife_horror',              label = 'Horror Knife',                       weapontype = 'Melee',        ammotype = nil,             damagereason = 'Cut by a horror knife' },
    [`weapon_melee_knife_rustic`]              = { name = 'weapon_melee_knife_rustic',              label = 'Rustic Knife',                       weapontype = 'Melee',        ammotype = nil,             damagereason = 'Cut by a rustic knife' },
    [`weapon_melee_machete`]                   = { name = 'weapon_melee_machete',                   label = 'Machete',                            weapontype = 'Melee',        ammotype = nil,             damagereason = 'Struck by a machete' },
    [`weapon_melee_machete_horror`]            = { name = 'weapon_melee_machete_horror',            label = 'Machete Horror',                     weapontype = 'Melee',        ammotype = nil,             damagereason = 'Struck by a horror machete' },
    [`weapon_melee_machete_collector`]         = { name = 'weapon_melee_machete_collector',         label = 'Machete Collector',                  weapontype = 'Melee',        ammotype = nil,             damagereason = 'Struck by a collector machete' },
    [`weapon_melee_torch`]                     = { name = 'weapon_melee_torch',                     label = 'Torch',                              weapontype = 'Melee',        ammotype = nil,             damagereason = 'Burned by a torch' },
    -- held
    [`weapon_melee_davy_lantern`]              = { name = 'weapon_melee_davy_lantern',              label = 'Davy Lantern',                       weapontype = 'Held',         ammotype = nil,             damagereason = 'Hit by a Davy lantern' },
    [`weapon_melee_lantern_halloween`]         = { name = 'weapon_melee_lantern_halloween',         label = 'Halloween Lantern',                  weapontype = 'Held',         ammotype = nil,             damagereason = 'Hit by a Halloween lantern' },
    [`weapon_kit_binoculars`]                  = { name = 'weapon_kit_binoculars',                  label = 'Binoculars',                         weapontype = 'Held',         ammotype = nil,             damagereason = 'Hit with binoculars' },
    [`weapon_kit_binoculars_improved`]         = { name = 'weapon_kit_binoculars_improved',         label = 'Improved Binoculars',                weapontype = 'Held',         ammotype = nil,             damagereason = 'Hit with improved binoculars' },
    [`weapon_kit_camera`]                      = { name = 'weapon_kit_camera',                      label = 'Camera',                             weapontype = 'Held',         ammotype = nil,             damagereason = 'Hit with a camera' },
    [`weapon_kit_camera_advanced`]             = { name = 'weapon_kit_camera_advanced',             label = 'Advanced Camera',                    weapontype = 'Held',         ammotype = nil,             damagereason = 'Hit with an advanced camera' },
    [`weapon_kit_metal_detector`]              = { name = 'weapon_kit_metal_detector',              label = 'Metal Detector',                     weapontype = 'Held',         ammotype = nil,             damagereason = 'Hit with a metal detector' },
    -- trown
    [`weapon_melee_hatchet`]                   = { name = 'weapon_melee_hatchet',                   label = 'Hatchet',                            weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Hit by a hatchet' },
    [`weapon_melee_hatchet_hunter`]            = { name = 'weapon_melee_hatchet_hunter',            label = 'Hunter Hatchet',                     weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Hit by a hunter hatchet' },
    [`weapon_melee_hatchet_double_bit`]        = { name = 'weapon_melee_hatchet_double_bit',        label = 'Double Bit Hatchet',                 weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Hit by a double bit hatchet' },
    [`weapon_thrown_molotov`]                  = { name = 'weapon_thrown_molotov',                  label = 'Molotov',                            weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Burned by a molotov' },
    [`weapon_thrown_tomahawk`]                 = { name = 'weapon_thrown_tomahawk',                 label = 'Tomahawk',                           weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Hit by a tomahawk' },
    [`weapon_thrown_tomahawk_ancient`]         = { name = 'weapon_thrown_tomahawk_ancient',         label = 'Tomahawk Ancient',                   weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Hit by an ancient tomahawk' },
    [`weapon_thrown_dynamite`]                 = { name = 'weapon_thrown_dynamite',                 label = 'Dynamite',                           weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Blasted by dynamite' },
    [`weapon_thrown_poisonbottle`]             = { name = 'weapon_thrown_poisonbottle',             label = 'Poison Bottle',                      weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Poisoned by a bottle' },
    [`weapon_thrown_throwing_knives`]          = { name = 'weapon_thrown_throwing_knives',          label = 'Throwing Kives',                     weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Hit by throwing knives' },
    [`weapon_melee_cleaver`]                   = { name = 'weapon_melee_cleaver',                   label = 'Cleaver',                            weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Hit by a cleaver' },
    [`weapon_thrown_bolas`]                    = { name = 'weapon_thrown_bolas',                    label = 'Balas',                              weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Hit by bolas' },
    [`weapon_thrown_bolas_hawkmoth`]           = { name = 'weapon_thrown_bolas_hawkmoth',           label = 'Hawkmoth Balas',                     weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Hit by Hawkmoth bolas' },
    [`weapon_thrown_bolas_ironspiked`]         = { name = 'weapon_thrown_bolas_ironspiked',         label = 'Iron Spiked Balas',                  weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Hit by iron spiked bolas' },
    [`weapon_thrown_bolas_intertwined`]        = { name = 'weapon_thrown_bolas_intertwined',        label = 'Intertwined Balas',                  weapontype = 'Thrown',       ammotype = nil,             damagereason = 'Hit by intertwined bolas' },
    -- fishing
    [`weapon_fishingrod`]                      = { name = 'weapon_fishingrod',                      label = 'Fishing Rod',                        weapontype = 'Fishing',      ammotype = nil,             damagereason = 'Hit by a fishing rod' },
}
